version: '3.8'

services:
  assignment_three:
    image: assignment_three:latest
    container_name: assignment_three
    ports:
      - "8080:8080"
    networks:
      - app-network

  demo:
    image: demo:latest
    container_name: demo
    ports:
      - "8081:8081"
    depends_on:
      - assignment_three
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
